list_user_ops_managed2:
  - user: ops51
  - user: ops52
  - user: ops53
  - user: ops54
  - user: ops55
  - user: ops56
  - user: ops57
  - user: ops58
  - user: ops59
  - user: ops60
  - user: ops61
  - user: ops62
  - user: ops63
  - user: ops64
  - user: ops65
  - user: ops66
  - user: ops67
  - user: ops68
  - user: ops69
  - user: ops70
  - user: ops71
  - user: ops72
  - user: ops73
  - user: ops74
  - user: ops75
  - user: ops76
  - user: ops77
  - user: ops78
  - user: ops79
  - user: ops80
  - user: ops81
  - user: ops82
  - user: ops83
  - user: ops84
  - user: ops85
  - user: ops86
  - user: ops87
  - user: ops88
  - user: ops89
  - user: ops90
  - user: ops91
  - user: ops92
  - user: ops93
  - user: ops94
  - user: ops95
  - user: ops96
  - user: ops97
  - user: ops98
  - user: ops99
  - user: ops100
list_user_dev_managed2:
  - user: dev51
  - user: dev52
  - user: dev53
  - user: dev54
  - user: dev55
  - user: dev56
  - user: dev57
  - user: dev58
  - user: dev59
  - user: dev60
  - user: dev61
  - user: dev62
  - user: dev63
  - user: dev64
  - user: dev65
  - user: dev66
  - user: dev67
  - user: dev68
  - user: dev69
  - user: dev70
  - user: dev71
  - user: dev72
  - user: dev73
  - user: dev74
  - user: dev75
  - user: dev76
  - user: dev77
  - user: dev78
  - user: dev79
  - user: dev80
  - user: dev81
  - user: dev82
  - user: dev83
  - user: dev84
  - user: dev85
  - user: dev86
  - user: dev87
  - user: dev88
  - user: dev89
  - user: dev90
  - user: dev91
  - user: dev92
  - user: dev93
  - user: dev94
  - user: dev95
  - user: dev96
  - user: dev97
  - user: dev98
  - user: dev99
  - user: dev100