list_user_ops_managed1:
  - user: ops1
  - user: ops2
  - user: ops3
  - user: ops4
  - user: ops5
  - user: ops6
  - user: ops7
  - user: ops8
  - user: ops9
  - user: ops10
  - user: ops11
  - user: ops12
  - user: ops13
  - user: ops14
  - user: ops15
  - user: ops16
  - user: ops17
  - user: ops18
  - user: ops19
  - user: ops20
  - user: ops21
  - user: ops22
  - user: ops23
  - user: ops24
  - user: ops25
  - user: ops26
  - user: ops27
  - user: ops28
  - user: ops29
  - user: ops30
  - user: ops31
  - user: ops32
  - user: ops33
  - user: ops34
  - user: ops35
  - user: ops36
  - user: ops37
  - user: ops38
  - user: ops39
  - user: ops40
  - user: ops41
  - user: ops42
  - user: ops43
  - user: ops44
  - user: ops45
  - user: ops46
  - user: ops47
  - user: ops48
  - user: ops49
  - user: ops50
list_user_dev_managed1:
  - user: dev1
  - user: dev2
  - user: dev3
  - user: dev4
  - user: dev5
  - user: dev6
  - user: dev7
  - user: dev8
  - user: dev9
  - user: dev10
  - user: dev11
  - user: dev12
  - user: dev13
  - user: dev14
  - user: dev15
  - user: dev16
  - user: dev17
  - user: dev18
  - user: dev19
  - user: dev20
  - user: dev21
  - user: dev22
  - user: dev23
  - user: dev24
  - user: dev25
  - user: dev26
  - user: dev27
  - user: dev28
  - user: dev29
  - user: dev30
  - user: dev31
  - user: dev32
  - user: dev33
  - user: dev34
  - user: dev35
  - user: dev36
  - user: dev37
  - user: dev38
  - user: dev39
  - user: dev40
  - user: dev41
  - user: dev42
  - user: dev43
  - user: dev44
  - user: dev45
  - user: dev46
  - user: dev47
  - user: dev48
  - user: dev49
  - user: dev50
